version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: companiondb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 